# Vertex AI Custom Job Configuration for Training
# 
# Usage:
#   gcloud ai custom-jobs create \
#     --region=europe-west1 \
#     --display-name="my-training-job" \
#     --config=vertex-ai/train-job.yaml \
#     --project=YOUR_PROJECT_ID
#
# Or use the helper script:
#   ./scripts/submit_training_job.sh

workerPoolSpecs:
  - machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    containerSpec:
      # Artifact Registry: europe-west1-docker.pkg.dev/PROJECT_ID/dtu-vibe-ops/dtu-vibe-ops-02476-train:latest
      # GCR: gcr.io/PROJECT_ID/dtu-vibe-ops-02476-train:latest
      imageUri: europe-west1-docker.pkg.dev/PROJECT_ID/dtu-vibe-ops/dtu-vibe-ops-02476-train:latest
      
      # Environment variables
      env:
        
        # W&B API key (if using W&B logging)
        # Set this via gcloud secrets or Vertex AI secrets manager
        # - name: WANDB_API_KEY
        #   value: "your-wandb-api-key"
      
      # Training script arguments (Hydra config overrides)
      # These are passed to the training script
      args:
        # Quick test configuration
        - data.subsample_percentage=0.01
        - training.max_epochs=2
        - wandb.enabled=false
